# import repo
- name: Add CouchDB repositories when os=cenos
  yum_repository:
    name: bintray-apache-couchdb-rpm
    file: bintray-apache-couchdb-rpm
    description: CouchDB RPM Repository
    baseurl: http://apache.bintray.com/couchdb-rpm/el$releasever/$basearch/
    gpgcheck: no
    enabled: yes
  when: ansible_distribution == "CentOS"

- name: Add CouchDB repositories when os=other
  yum_repository:
    name: bintray-apache-couchdb-rpm
    file: bintray-apache-couchdb-rpm
    description: CouchDB RPM Repository
    baseurl: http://apache.bintray.com/couchdb-rpm/el{{ansible_distribution_major_version}}/$basearch/
    gpgcheck: no
    enabled: yes
  when: ansible_distribution != "CentOS"

# install couchdb
- name: Install CouchDB
  yum:
    name: couchdb
    update_cache: yes
  
